# Configuration for SIC Evaluation 

[paths]
batch_filepath = "gs://<your-location-here>/evaluation_data/retries.csv"
output_filepath = "gs://<your-location-here>/"

local_json_dir = "/home/user/survey-assist-utils/data/json_runs"
gcs_bucket_name = "<your_bucket_location>"
gcs_prefix = "analysis_outputs/"
processed_csv_output = "gs://<your-location-here>/analysis_outputs/added_columns/sic_dataframe_with_flags.csv"
# "/home/user/survey-assist-utils/data/evaluation_data/sic_dataframe_with_flags.csv" # this file must already have Unambiguous added to it
# "/<your-location-here>/analysis_outputs/added_columns" # bucket location of unambiguous

# Location of merged data:
# gs://<your-location-here>/analysis_outputs/merged_files/.csv


[parameters]
test_mode = false
test_num = 0
rows_to_skip = 0

date_since = "20250522"
max_candidates = 5

[json_keys]
unique_id = "unique_id"
#  'classified': 'classified',
#  'followup': 'followup',
#  'source_sic_code': 'sic_code',
#  'source_sic_description': 'sic_description',
#  'reasoning': 'reasoning',
#  'payload_path': 'request_payload',
#  'payload_job_title': 'job_title',
#  'payload_job_description': 'job_description',
#  'candidates_path': 'sic_candidates',
#  'candidate_sic_code': 'sic_code',
#  'candidate_description': 'sic_descriptive',
#  'candidate_likelihood': 'likelihood'},


[column_names]
payload_unique_id = "unique_id"
payload_job_title = "soc2020_job_title"
payload_job_description = "soc2020_job_description"
payload_industry_description = "sic2007_employee"


unique_id = "unique_id"
sic_ind_occ1 = "sic_ind_occ1"         # Analysis SIC code column
sic_ind_occ2 = "sic_ind_occ2"         # Analysis SIC code column
sic_ind_occ3 = "sic_ind_occ3"         # Analysis SIC code column
coding_flag = "sic_ind_code_flag"   # Analysis column for KB/CC/MC flag

