
# Configuration for Preprocessing and Evaluation

[paths]
batch_filepath = "gs://<insert-location>/evaluation_data/TLFS_evaluation_data_IT2.csv"
output_filepath = "gs://<insert-location>/"
# processed_csv_output = "gs://<your-location-here>/analysis_outputs/added_columns/sic_dataframe_with_flags.csv"
# "/home/user/survey-assist-utils/data/evaluation_data/sic_dataframe_with_flags.csv" # this file must already have Unambiguous added to it
# "/<your-location-here>/analysis_outputs/added_columns" # bucket location of unambiguous

# Location of merged data:
# gs://<your-location-here>/analysis_outputs/merged_files/.csv
# Local directory where raw JSON files are stored
local_json_dir = "/home/user/survey-assist-utils/data/json_runs"
# GCS bucket and folder for raw JSON files
gcs_bucket_name = "<your_bucket_location>"
gcs_prefix = "analysis_outputs/"
# Output for the final processed CSV
processed_csv_output = "/home/user/survey-assist-utils/data/analysis_outputs/TLFS_evaluation_data_IT2_output.csv"

[parameters]
# Process only files created on or after this date (YYYYMMDD)
date_since = "20250522"
# Max number of LLM candidates to process per record
max_candidates = 5
test_mode = false
test_num = 0
rows_to_skip = 0


[json_keys]
unique_id = "unique_id"
classified = "classified"
followup = "followup"
source_sic_code = "sic_code"
source_sic_description = "sic_description"
reasoning = "reasoning"

# --- Nested payload keys ---
payload_path = "request_payload"
payload_job_title = "job_title"
payload_job_description = "job_description"

# --- Nested candidate keys ---
candidates_path = "sic_candidates"
candidate_sic_code = "sic_code"
candidate_description = "sic_descriptive"
candidate_likelihood = "likelihood"

[column_names]
payload_unique_id = "unique_id"
payload_job_title = "soc2020_job_title"
payload_job_description = "soc2020_job_description"
payload_industry_description = "sic2007_employee"


[logging]
level = "INFO"
format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

